#!/bin/sh
### BEGIN INIT INFO
# Provides:          resize2fs_once
# Required-Start:
# Required-Stop:
# Default-Start: 3
# Default-Stop:
# Short-Description: Resize the root filesystem to fill partition
# Description:
### END INIT INFO
. /lib/lsb/init-functions
case "$1" in
  start)
    log_daemon_msg "Starting resize2fs_once"
    ROOT_DEV=`grep -Eo 'root=[[:graph:]]+' /proc/cmdline | cut -d '=' -f 2-` &&
    log_daemon_msg "Recreating linux partition to maximum size..."
    echo ",+," | sfdisk -N2 /dev/mmcblk0
    partprobe
    log_daemon_msg "Resizing linux filesystem to maximum partition size..."
    resize2fs $ROOT_DEV &&
    log_daemon_msg "This service shall self-destruct in 3... 2... 1... *boom*"
    update-rc.d resize2fs_once remove &&
    rm /etc/init.d/resize2fs_once &&
    log_daemon_msg "Reloading systemctl daemon now since one of the init.d scripts is gone..."
    systemctl daemon-reload
    log_end_msg $?
    ;;
  *)
    echo "Usage: $0 start" >&2
    exit 3
    ;;
esac
