#!/bin/sh
. /lib/lsb/init-functions

case "${1}" in
    start)
        start-stop-daemon --start --background --exec /usr/libexec/bluetooth/bluetoothd
    ;;

    stop)
        start-stop-daemon --stop --background --exec /usr/libexec/bluetooth/bluetoothd
    ;;

    restart)
        ${0} stop
        sleep 1
        ${0} start
    ;;

    *)

        echo "Usage: ${0} {start|stop|restart}"
        exit 1

    ;;
esac

exit 0
